apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-httpd
  name: deploy-httpd
spec:
  replicas: 10
  selector:
    matchLabels:
      app: deploy-httpd
  template:
    metadata:
      labels:
        app: deploy-httpd
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
  strategy:
    type: Recreate
